version: "3.7"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=<022>
    volumes:
      - ./syncthing:/config
      - /mnt/storage/music:/music
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

  mpd:
    image: tobi312/rpi-mpd:debian
    container_name: mpd
    volumes:
      - ./mpd/conf/mpd.conf:/etc/mpd.conf
      - ./mpd/data:/mpd/data:rw
      - ./mpd/playlists:/mpd/playlists:rw
      - /mnt/storage/music:/music:ro
    devices:
      - /dev/snd:/dev/snd
    ports:
      - 6600:6600
      - 8000:8000
    restart: unless-stopped
